### ISSUE TITLE
binary_sensor stops working after two days

### ISSUE THREAD

**Issue by marceldeklerk** [plaksnor/HASS-JablotronSystem#7]
I haven't properly investigated my issue yet, but my Jablotron binary_sensors (motion and magnetic) just stop updating after two days of running the custom_component. I am not entirely sure what had triggered this. A hass restart solves the issue for ~ 2days.

I changed a lot recently:
- Migrated HASS to a new version, new Raspberry Pi.
- Updated to latest version of JablotronSystem component.
- Added a smoke detector to my Jablotron security system.

I expect that the last one is causing my issues. 
Also i've noticed that whenever the component is working, movements detected by my PIR's are not always catched by the binary_sensor. The magnetic door contact binary_sensors does not have this issue, and works flawlessly.

Anyone else experiencing the same? 
I will investigate this soon.

oh, btw: the alarm_control_panel is not impacted, and continues to function properly.

**Comment by Shamshala** [comment]
Have you tried to look into logs in debug mode?
```
logger:
  logs:
    custom_components.jablotron_system: debug
    custom_components.jablotron_system.alarm_control_panel: debug
```
